# YAML aint markup language

input_file: '../Datasets/DJIA/Intel.csv'
output_file: '../Datasets/DJIA/newIntel.csv'
companyDataAddress: '../Datasets/Companies 2017/Intel.csv'
outputCompanyDataAddress: '../Datasets/New Companies/Intel.csv'






person:
	name: "saaaaaad"
	occupation: "pro"
	age: 21
	gpa: 3.8
	fav_num: 1e+10
	male: true
	birthday: 1998-03-16 14:33:22
	flaws: null
	hobbies:
		-hiking
		-movies
		-riding bike
	movies: ["Dark Knight","Good Will Hunting"]
	friends:
		-name:"Steph"
		 age:22
		-{name:"Adam",age:22}
		-
		  name: "joe"
		  age: 23

